# Generated by Django 5.2.4 on 2025-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text='Enter the author name', max_length=100)),
                ('publication_year', models.IntegerField(help_text='Enter the year of publication')),
            ],
        ),
    ]
